### PR TITLE
Npm package

### PR DESCRIPTION
**Pull request by mstade**
Restructured to prepare for npm publishing.

This removes all component stuff, moves all dependencies to
npm style package.json dependencies and fixes the tests to run
under node.

### CODE REVIEW

**Comment by mstade** [comment]
I'd like to hook this up to some sort of CI and possibly test coverage as much, much like I did with [funkis][1], before anything gets merged. Also, should probably look into getting some browser coverage in before anything is published.

[1]: https://github.com/mstade/funkis

**Comment by mstade** [comment]
@aaronhaines this mostly prepares rhumb for npm I think, but I'd like to look into setting up a better test environment, since the current one using mocha and stuff is a bit inconvenient. Also, I'd like to set up CI and code coverage at some point. Do you reckon it's worth looking into that now, or should we just publish as-is for now to see about moving things over to the public npm?

(This branch does *not* include #3 btw. I figured I'd get it npm ready first, then deal with PRs.)

**Comment by sammyt** [comment]
:+1: looks good to me.  The travis setup you (@mstade) have with funkis looks great

**Comment by mstade** [comment]
He's alive! :o)

Travis is nice, and simple to set up. I've also been looking at [wercker][1] which has the interesting feature that in addition to setting up build steps you also define boxes, which are just docker containers really. It's interesting for all the reasons it was interesting to have a consistent development environment using Vagrant – no surprises when your hosted CI decides to change infrastructure. Anyway, either will do, frankly. I'll look into it, but possibly in a different branch.

[1]: http://wercker.com

**Comment by mstade** [comment]
[Rhumb is now on npm][1]! I conveniently ignored the discussion re: scopes in sammyt/nap#10, but should we want to publish this under a scope we ought to do it sooner rather than later I think.

[1]: https://www.npmjs.com/package/rhumb

I need to update usage docs, but this should work in both node and a browser since it's a UMD build. In node it's a typical `npm i rhumb` and in a browser it's a matter of either picking out `lib/rhumb.js` and placing it somewhere, or digging through the typical node_modules structure. I don't really know how or if we'd like to provide some better distribution method for browsers, or if there's a standard practice to be had here. Any input on that would be most welcome!

**Comment by mstade** [comment]
@pemrouz, I'd love to look into using [Popper] for browser tests – any guidance you could provide?

[Popper]: https://github.com/pemrouz/popper

**Comment by mstade** [comment]
Well I'll be damned, [wercker now has support for local development][1] akin to what you'd have with Vagrant or similar tooling. That's pretty killer, I might just go ahead and try that. I'll create new issues for the things I've raised in this PR, and consider this one ready to be merged unless anyone disagrees.

[1]: http://blog.wercker.com/2015/05/15/Introducing-local-development.html

**Comment by mstade** [comment]
I've opened up issues #7, #8, and #9 to track discussions and future work on the points raised in this PR. I'd say this is ready to merge at will, and the rest of the bridges will be burned as we get to them. :o)

**Comment by pemrouz** [comment]
@mstade - sure, I'll open PR later today re:popper to get things started.

**Comment by mstade** [comment]
Very cool @pemrouz – thanks! :o)

**Comment by mstade** [comment]
Because I, much like @sammyt, am a cowboy; I'm just gonna go ahead and merge this and get on with the other things. (Such as finally reviewing and merging #3!) Feel free to raise any issues that may come up and I'll get right on it.

**Comment by sammyt** [comment]
> Because I, much like @sammyt, am a cowboy; I'm just gonna go ahead and merge this and get on with the other things

@sammyt approves of this philosophy

**Comment by mstade** [comment]
Haha! :heart:

**Pull request merged**
